.TH PRINTF 1 "26 April 2023" "Usage"
.SH NAME
printf \- format and print texts
.SH SYNOPSIS
.B printf
[\fBFORMAT\fR]
[\fBARGUMENT\fR]
.IR ...
.SH DESCRIPTION
Prints a formated text. This program works in a similar way to C printf and as
such, handles all its format and include its own sets of FORMAT listed below:
.TP
.P
\fB%r\fR reverse of a string
.P
\fB%R\fR encrypts using ROT-13
.P
\fB%S\fR string in uppercase and hexadecimal
.SH AUTHORS
Written by Leo Emaxie and Toluwani Ojukutu



